- name: Add the user
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    password: "{{ item.password }}"
    update_password: always
    group: "sudo"
    shell: /bin/bash
    create_home: yes
    state: "{{ item.state }}"
    remove: yes
  with_items: "{{ users }}"

- name: Add the user key
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "https://github.com/{{ item.name }}.keys"
    validate_certs: false
  with_items: "{{ users }}"
